version: "3.9"
services:
  app:
    build: .
    image: rate-limiter:dev
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=75"
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks: [stack]

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks: [stack]

  prometheus:
    image: prom/prometheus:v2.54.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
    ports:
      - "9090:9090"
    networks: [stack]

  grafana:
    image: grafana/grafana:11.1.0
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    networks: [stack]

networks:
  stack: {}
