global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'rate-limiter'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['app:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
